### ISSUE TITLE
mount source /usr/local/var/lib/arriba doesn't exist

### ISSUE THREAD

**Issue by wudustan** [nf-core/rnafusion#286] opened 2022-12-08 13:55 UTC
### Description of the bug

While running netxflow rnafusion I get the following error:

`mount source /usr/local/var/lib/arriba doesn't exist`
Can you help me understand what's going wrong?

### Command used and terminal output

Full error message:
```
FATAL:   container creation failed: mount /usr/local/var/lib/arriba->/usr/local/var/lib/arriba error: while mounting /usr/local/var/lib/arriba: mount source /usr/local/var/lib/arriba doesn't exist
```
It appears to be related to this section of `.command.run`

```
nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} SINGULARITYENV_NXF_DEBUG=${NXF_DEBUG:=0} singularity exec -B /.../nf-core-rnafusion -B /usr/
local/var/lib/arriba /.../nf-core-rnafusion/workflow/../singularity-images/depot.galaxyproject.org-singularity-arriba-2.3.0--haa8aa89_0.img /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash
/.../nf-core-rnafusion/work/86/57d963992ef64aea2a79ced13641d7/.command.run nxf_trace"
}
```

I used Vagrant to inspect the image `depot.galaxyproject.org-singularity-arriba-2.3.0--haa8aa89_0.img`

```
vagrant@vagrant:~$ singularity exec depot.galaxyproject.org-singularity-arriba-2.3.0--haa8aa89_0.img /bin/bash -c "ls /usr/local/var/lib/arriba"
CREDITS                                         cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv         known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz  protein_domains_mm10_GRCm38_v2.3.0.gff3
RefSeq_viral_genomes_v2.3.0.fa.gz               cytobands_hg38_GRCh38_v2.3.0.tsv                known_fusions_hg38_GRCh38_v2.3.0.tsv.gz         protein_domains_mm39_GRCm39_v2.3.0.gff3
blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz      cytobands_mm10_GRCm38_v2.3.0.tsv                known_fusions_mm10_GRCm38_v2.3.0.tsv.gz         read1.fastq.gz
blacklist_hg38_GRCh38_v2.3.0.tsv.gz             cytobands_mm39_GRCm39_v2.3.0.tsv                known_fusions_mm39_GRCm39_v2.3.0.tsv.gz         read2.fastq.gz
blacklist_mm10_GRCm38_v2.3.0.tsv.gz             download_references.sh                          protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3
blacklist_mm39_GRCm39_v2.3.0.tsv.gz             fusions.tsv                                     protein_domains_hg38_GRCh38_v2.3.0.gff3
vagrant@vagrant:~$
```

Command call to run pipeline
```
nextflow run /.../nf-core-rnafusion/workflow -profile singularity --all \
--genomes_base /.../nf-core-rnafusion/genomes_base \
--input /.../nf-core-rnafusion/samplesheets/pilot.csv \
--outdir /.../nf-core-rnafusion/results
```

### Relevant files

[nextflow.log](https://github.com/nf-core/rnafusion/files/10185983/nextflow.log)

### System information

nextflow 22.10.1.5828
nf-core/rnafusion v2.1.0

Hardware: HPC
Executor: Slurm
Container engine: Singularity
OS: CentOS

**Comment by apeltzer** [comment] 2022-12-08 14:26
Duplicate of https://github.com/nf-core/rnafusion/issues/283

**Closed by apeltzer** 2022-12-08 14:26 UTC
Labels: bug
