### ISSUE TITLE
prep_genome_lib.pl bug

### ISSUE THREAD

**Issue by valleema** [nf-core/rnafusion#106] opened 2020-02-10 14:20 UTC
Hello,

not sure this one is for you or for https://github.com/NCIP/ctat-genome-lib-builder/

When I want to download star-fusion references, the `.command.sh` holds:

```
prep_genome_lib.pl \
    --genome_fa Homo_sapiens.GRCh38_r99.all.fa \
    --gtf Homo_sapiens.GRCh38_r99.gtf \
    --fusion_annot_lib CTAT_HumanFusionLib.dat.gz \
    --annot_filter_rule AnnotFilterRule.pm \
    --pfam_db Pfam-A.hmm \
    --dfam_db homo_sapiens_dfam.hmm \
    --human_gencode_filter \
    --CPU 12
```

It is dying here:

```
* Running CMD: bash -c "set -euxo pipefail; cat /home/valleemax/bin/rnafusion/work/6a/f6fda67696763ef568142691b05b0a/Homo_sapiens.GRCh38_r99.gtf | egrep 'IG_V_gene|IG_C_gene|IG_D_gene|IG_J_gene' | awk '{ if (\$3 == \"exon\") { print } }' | egrep ^chr14  > __gencode_refinement_chkpts/IGH_locus.gtf"
+ cat /home/valleemax/bin/rnafusion/work/6a/f6fda67696763ef568142691b05b0a/Homo_sapiens.GRCh38_r99.gtf
+ egrep 'IG_V_gene|IG_C_gene|IG_D_gene|IG_J_gene'
+ awk '{ if ($3 == "exon") { print } }'
+ egrep '^chr14'
Error, cmd: bash -c "set -euxo pipefail; cat /home/valleemax/bin/rnafusion/work/6a/f6fda67696763ef568142691b05b0a/Homo_sapiens.GRCh38_r99.gtf | egrep 'IG_V_gene|IG_C_gene|IG_D_gene|IG_J_gene' | awk '{ if (\$3 == \"exon\") { print } }' | egrep ^chr14  > __gencode_refinement_chkpts/IGH_locus.gtf" died with ret 256 No such file or directory at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/util/../lib/Pipeliner.pm line 186.
        Pipeliner::run(Pipeliner=HASH(0x557998940100)) called at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/util/revise_gencode_annotations.pl line 114
Error, cmd: /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/util/revise_gencode_annotations.pl --gencode_gtf /home/valleemax/bin/rnafusion/work/6a/f6fda67696763ef568142691b05b0a/Homo_sapiens.GRCh38_r99.gtf --out_gtf /home/valleemax/bin/rnafusion/work/6a/f6fda67696763ef568142691b05b0a/Homo_sapiens.GRCh38_r99.gtf.revised.gtf died with ret 512 No such file or directory at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/lib/Pipeliner.pm line 186.
        Pipeliner::run(Pipeliner=HASH(0x561212e00f90)) called at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625//prep_genome_lib.pl line 451
```

Because it is trying to `egrep ^chr14`, but in the downloaded GTF, the chromosomes are without chr. thus, this line ends up creating nothing:

```
set -euxo pipefail; cat /home/valleemax/bin/rnafusion/work/6a/f6fda67696763ef568142691b05b0a/Homo_sapiens.GRCh38_r99.gtf | egrep 'IG_V_gene|IG_C_gene|IG_D_gene|IG_J_gene' | awk '{ if ($3 == "exon") { print } }' | egrep ^chr14  > __gencode_refinement_chkpts/IGH_locus.gtf
```

Removing the "chr" in the command creates a 230-lines file.

I made a quick fix to test in the work dir: I added with `awk` chr in front of every line of the GTF, it seems to work at first, but it fails further down the line.

**Comment by matq007** [comment] 2020-02-10 14:30
Can you try it with version 97? That is the one I have been using in this release

**Comment by matq007** [comment] 2020-02-10 14:33
Ah I think I know where the issue is. Can you try this
```
prep_genome_lib.pl \\
        --genome_fa ${fasta} \\
        --gtf ${gtf} \\
        --fusion_annot_lib CTAT_HumanFusionLib.dat.gz \\
        --annot_filter_rule AnnotFilterRule.pm \\
        --pfam_db Pfam-A.hmm \\
        --dfam_db homo_sapiens_dfam.hmm \\
        --CPU ${task.cpus}
```

**Comment by valleema** [comment] 2020-02-10 14:35
Would you like I try this code with version 97 or 99?

**Comment by matq007** [comment] 2020-02-10 14:39
I think it doesn't matter any more as long as you don't use `--human_gencode_filter`. I have missed this when resolving merge conflicts

**Comment by valleema** [comment] 2020-02-10 14:39
OK I have launched the edited NF with 99, I will report back.

**Comment by matq007** [comment] 2020-02-11 09:54
Hi, any update on the script? :)

**Comment by valleema** [comment] 2020-02-11 11:44
I had hit a walltime yesterday evening with fusioncatcher reference downloads, so it failed. 

I have re-launched it this morning (exteding walltimes) at 7:13am, and it is still running... It looks frozen (I cannot log directly on the computing node to check).

Last logged lines from 8:29am:

```
tail .command.err
Warning: Skipping ENSG00000286522 (five_prime_utr) as this gene is already included as a coding gene.
Warning: Skipping ENSG00000112799 (five_prime_utr) as this gene is already included as a coding gene.
Warning: Skipping ENSG00000166984 (five_prime_utr) as this gene is already included as a coding gene.
Warning: Skipping ENSG00000164465 (five_prime_utr) as this gene is already included as a coding gene.
Warning: Skipping ENSG00000137161 (five_prime_utr) as this gene is already included as a coding gene.
Warning: Skipping ENSG00000153303 (five_prime_utr) as this gene is already included as a coding gene.
Warning: Skipping ENSG00000111886 (five_prime_utr) as this gene is already included as a coding gene.
Warning: Skipping ENSG00000026297 (five_prime_utr) as this gene is already included as a coding gene.
* Running CMD: /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/util/dfam_repeat_masker.pl --dfam_hmm homo_sapiens_dfam.hmm --target_fa ref_annot.cdsplus.fa --out_masked ref_annot.cdsplus.dfam_masked.fa --CPU 12
* Running CMD: dfamscan.pl -fastafile ref_annot.cdsplus.fa -hmmfile homo_sapiens_dfam.hmm -dfam_outfile __dfam_ref_annot.cdsplus.fa/dfam.out --masking_thresh --cpu 12
```

**Comment by valleema** [comment] 2020-02-12 07:23
So, even after a night of runtime it has not gone farther at all.

I took the last hanging command:

```
* Running CMD: dfamscan.pl -fastafile ref_annot.cdsplus.fa -hmmfile homo_sapiens_dfam.hmm -dfam_outfile __dfam_ref_annot.cdsplus.fa/dfam.out --masking_thresh --cpu 12
```

And tried it directly to see if there is any problem with the singularity image:

```
singularity exec ../../singularity/rnafusion_star-fusion_v1.6.0.img dfamscan.pl --version
/opt/conda/envs/star-fusion_v1.6.0/bin/dfamscan.pl : version 1.4
        nhmmscan : version HMMER 3.2.1 (June 2018)
```

This seems to work. So for the command:

```
singularity exec ../../singularity/rnafusion_star-fusion_v1.6.0.img dfamscan.pl -fastafile ref_annot.cdsplus.fa -hmmfile homo_sapiens_dfam.hmm -dfam_outfile __dfam_ref_annot.cdsplus.fa/dfam.out --masking_thresh --cpu 12
``` 

It is running for half and hour, and no stderr or stdout at all. No new file created as well.

**Comment by valleema** [comment] 2020-02-12 08:46
Update. When I CTRL-C the command, one command popped up, complaining that I had cut it.

```
nhmmscan --noali --cut_ga --dfamtblout /tmp/Iuhg
G47Jvk --cpu=1 homo_sapiens_dfam.hmm ref_annot.cdsplus.fa
```

It is running and writing in /tmp... Very slow then...

Why cannot we use the plug n play version, like the one before? It seems a huge amount of work just for references.

**Comment by matq007** [comment] 2020-02-12 08:48
The problem is that you would mix NCBI and Ensembl reference. I will have a look at it. I was able to build the reference but clearly there have been some new updated on the way.

**Comment by valleema** [comment] 2020-02-12 08:49
How long did the `dowload_star_fusion` process took for you?

**Comment by matq007** [comment] 2020-02-12 08:51
If I remember correctly the whole thing took 12 hours in total.

**Comment by matq007** [comment] 2020-02-12 08:52
We will try these steps again on the server. I won't lie, I haven't tested the download script after that one successful download. I will decipher the download again and report back soon. I have some old notes from it somewhere

**Comment by valleema** [comment] 2020-02-12 09:00
OK. The other processes are quite fast and thanks to the resume they do not pop up again. I added the `--outTmpDir` of `prep_genome_lib.pl` to see if I can better monitor files.

**Comment by valleema** [comment] 2020-02-13 06:16
The `dfamscan.pl` command went through with a longer walltime, however another command has failed and killed the job after a 15h runtime :(

```
tail .command.err
-storing ENSG00000164841
        -also storing TMEM74
-storing ENSG00000185640
        -also storing KRT79
-storing ENSG00000105122
        -also storing RASAL3
* Running CMD: cp AnnotFilterRule.pm /home/valleemax/bin/rnafusion/work/73/51e8326a532e53f2a80b37db403f8f/ctat_genome_lib_build_dir/.
cp: cannot stat 'AnnotFilterRule.pm': No such file or directory
Error, cmd: cp AnnotFilterRule.pm /home/valleemax/bin/rnafusion/work/73/51e8326a532e53f2a80b37db403f8f/ctat_genome_lib_build_dir/. died with ret 256 No such file or directory at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/lib/Pipeliner.pm line 186.
        Pipeliner::run(Pipeliner=HASH(0x55a79578e0b0)) called at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/prep_genome_lib.pl line 451
```

**Comment by valleema** [comment] 2020-02-18 06:40
Any news on this bug?

**Comment by matq007** [comment] 2020-02-18 07:15
Still in progress, @MaxUlysse is running it on internal server.

**Comment by valleema** [comment] 2020-02-18 07:16
Ok Thanks!

**Comment by matq007** [comment] 2020-02-20 08:56
Hey @valleema, I have updated the download script. It should work now hopefully :)

**Comment by valleema** [comment] 2020-02-20 13:21
Ok I will try and report!

**Comment by valleema** [comment] 2020-02-21 06:19
Got this error:

```
  * Running CMD: bash -c " set -euxo pipefail; /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/util/gtf_to_exon_gene_records.pl ctat_genome_lib_build_dir/ref_annot.gtf  | sort -k 1,1 -k4,4g -k5,5g | uniq  > ctat_genome_lib_build_dir/ref_annot.gtf.mini.sortu "
  + /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/util/gtf_to_exon_gene_records.pl ctat_genome_lib_build_dir/ref_annot.gtf
  + sort -k 1,1 -k4,4g -k5,5g
  + uniq
  * Running CMD: STAR --runThreadN 12 --runMode genomeGenerate --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx   --genomeFastaFiles Homo_sapiens.GRCh38_r99.all.fa  --limitGenomeGenerateRAM 40419136213  --genomeChrBinNbits 16  --sjdbGTFfile Homo_sapiens.GRCh38_r99.gtf  --sjdbOverhang 150

  EXITING because of FATAL problem while generating the suffix array
  The number of indices read from chunks = 5078959255 is not equal to expected nSA=5869753986
  SOLUTION: try to re-run suffix array generation, if it still does not work, report this problem to the author

  Feb 20 14:43:18 ...... FATAL ERROR, exiting
  Error, cmd: STAR --runThreadN 12 --runMode genomeGenerate --genomeDir ctat_genome_lib_build_dir/ref_genome.fa.star.idx   --genomeFastaFiles Homo_sapiens.GRCh38_r99.all.fa  --limitGenomeGenerateRAM 40419136213  --genomeChrBinNbits 16  --sjdbGTFfile Homo_sapiens.GRCh38_r99.gtf  --sjdbOverhang 150  died with ret 26624 No such file or directory at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/lib/Pipeliner.pm line 186.
        Pipeliner::run(Pipeliner=HASH(0x563073a378b8)) called at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/prep_genome_lib.pl line 451
```

**Comment by matq007** [comment] 2020-02-21 09:12
Can you please use: r97. This is the one I am building with without any issues.

**Comment by valleema** [comment] 2020-02-21 09:15
Ok, I try 97, and I will report.

**Comment by valleema** [comment] 2020-02-21 10:45
Same :

```
* Running CMD: STAR --runThreadN 12 --runMode genomeGenerate --genomeDir /home/valleemax/bin/rnafusion/work/1d/f09ef499e979c94deed147493a9745/ctat_genome_lib_build_dir/ref_genome.fa.star.idx   --genomeFastaFiles /home/valleemax/bin/rnafusion/work/1d/f09ef499e979c94deed147493a9745/Homo_sapiens.GRCh38_r97.all.fa  --limitGenomeGenerateRAM 40419136213  --genomeChrBinNbits 16  --sjdbGTFfile /home/valleemax/bin/rnafusion/work/1d/f09ef499e979c94deed147493a9745/Homo_sapiens.GRCh38_r97.gtf  --sjdbOverhang 150

EXITING because of FATAL problem while generating the suffix array
The number of indices read from chunks = 2936637298 is not equal to expected nSA=5869753986
SOLUTION: try to re-run suffix array generation, if it still does not work, report this problem to the author

Feb 21 10:02:06 ...... FATAL ERROR, exiting
Error, cmd: STAR --runThreadN 12 --runMode genomeGenerate --genomeDir /home/valleemax/bin/rnafusion/work/1d/f09ef499e979c94deed147493a9745/ctat_genome_lib_build_dir/ref_genome.fa.star.idx   --genomeFastaFiles /home/valleemax/bin/rnafusion/work/1d/f09ef499e979c94deed147493a9745/Homo_sapiens.GRCh38_r97.all.fa  --limitGenomeGenerateRAM 40419136213  --genomeChrBinNbits 16  --sjdbGTFfile /home/valleemax/bin/rnafusion/work/1d/f09ef499e979c94deed147493a9745/Homo_sapiens.GRCh38_r97.gtf  --sjdbOverhang 150  died with ret 26624 No such file or directory at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/lib/Pipeliner.pm line 186.
        Pipeliner::run(Pipeliner=HASH(0x5557c2455158)) called at /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/prep_genome_lib.pl line 451
```

**Comment by matq007** [comment] 2020-02-24 07:17
Do you have enough space on the disk? I found similar issue here: https://github.com/alexdobin/STAR/issues/534

**Comment by valleema** [comment] 2020-02-25 06:15
I tried it again, I have extended the walltime to 20 hours, and yet it is still not enough.

```
* Running CMD: cp ref_annot.cdna.fa /bettik/valleemax/rnafusion_ref/work/fd/0b5380e850d168d90cd7d1f3dd7732/ctat_genome_lib_build_dir/ref_annot.cdna.fa
* Running CMD: /opt/conda/envs/star-fusion_v1.6.0/ctat-genome-lib-builder-2830cd708c5bb9353878ca98069427e83acdd625/util/index_cdna_seqs.pl /bettik/valleemax/rnafusion_ref/work/fd/0b5380e850d168d90cd7d1f3dd7732/ctat_genome_lib_build_dir/ref_annot.cdna.fa
-done creating index file: /bettik/valleemax/rnafusion_ref/work/fd/0b5380e850d168d90cd7d1f3dd7732/ctat_genome_lib_build_dir/ref_annot.cdna.fa.idx

* Running CMD: makeblastdb -in ref_annot.cdna.fa -dbtype nucl
* Running CMD: blastn -query ref_annot.cdna.fa -db ref_annot.cdna.fa -max_target_seqs 10000 -outfmt 6 -evalue 1e-10 -num_threads 12 -dust no > ref_annot.cdna.fa.allvsall.outfmt6
## OAR [2020-02-25 04:52:33] Job 5735949 KILLED ##
```

I will launch it again with a longer walltime...

**Comment by MaxUlysse** [comment] 2020-02-25 06:39
Good luck with that, I had some issues as well, it's now ongoing, and I hope to report soon that it works for me as well without failure.

**Comment by valleema** [comment] 2020-02-25 06:44
@MaxUlysse haha that is not very encouraging! 

Is there no way to use the pipeline with the plug n play ref, like the previous release?

**Comment by MaxUlysse** [comment] 2020-02-25 06:49
Sorry, I did not want to alarm you, by other issues, I meant issues with other pipelines.
We're currently working with Martin to transfer the responsibility of this pipeline to me.
But I do hope we'll making to make this part easier.

**Comment by valleema** [comment] 2020-02-25 06:54
Ah yes, understood!

Yes I really think the pipeline is great because I tried the previous release without hard hurdles besides some configuration fiddling, and I have good results with it.

Now it has been 15 days and I have not even been able to try the new release, because of the download references step.

**Comment by MaxUlysse** [comment] 2020-02-25 06:56
I can see the issue, and I'm really sorry for that.

**Comment by valleema** [comment] 2020-02-25 06:57
It is OK, I see you guys are doing a lot for the community, and I thank you for that.

**Comment by matq007** [comment] 2020-02-25 07:15
From all the log messages it looks like its working just takes ages to finish.... I am thinking if we should increase CPU to 20 and time to 48h....

**Comment by valleema** [comment] 2020-02-25 07:19
Would it be feasible to generate once on your side, then pack it into a docker/singularity image for future pipeline users?

I am, in parallel, trying out nf-core/rnaseq and with one command line I was able to launch an analysis.

**Comment by matq007** [comment] 2020-02-25 07:31
We have just started discussion on it with @MaxUlysse, we will see if we can incorporate it to igenomes. Sorry for all the trouble ...

**Comment by valleema** [comment] 2020-02-25 07:33
Oooh yes igenomes would be excellent. Again, no problem, I like all the support and efforts you guys give.

**Comment by matq007** [comment] 2020-02-25 07:38
Ok, we have just launched tar/xz compression on the 47GB reference folder, let's see how much we can squeeze it.

**Comment by MaxUlysse** [comment] 2020-02-26 15:22
Some updates:
- I did manage to run the script without any issue on my side, so I can say that it is working. I just know that it took more than 10h, I'm sorry I couldn't get more precise metrics about it, as I was running it outside Nextflow, and did not really planned to measure anything actually.
- I compressed the folder with tar/xz compression,  and the size is now to 30G
- I spoke with @ewels about having it on iGenomes, and it's doable

**Comment by valleema** [comment] 2020-02-27 06:15
@MaxUlysse great news!

On my side I pushed the walltime to the max possible on the cluster I use, and the job was cut anyway.

It was doing this when it was cut:

```
* Running CMD: hmmscan --cpu 4 --domtblout PFAM.domtblout.dat Pfam-A.hmm ref_annot.pep.fa
```

I will be on the lookout for your iGenomes integration 👍

**Comment by matq007** [comment] 2020-04-18 09:04
x-ref: #109

**Closed by matq007** 2020-04-18 09:04 UTC
Labels: bug
