### ISSUE TITLE
  ARRIBA_VISUALISATION  : Process exceeded running time limit (8h)

### ISSUE THREAD

**Issue by ZheFrench** [nf-core/rnafusion#449] opened 2023-11-28 10:24 UTC
### Description of the bug

  Process exceeded running time limit of (8h) for visualisation.

That's weird it's taking so long. It was a recurrent one.
I don't know if it's worth increasing running time here or it's just freezing indefinitely.

I finally ended up to set -resume with --skip_vis will to avoid the error.
WRONG ANSWER : It will create only an empty fill for fusion report...

```
nov.-28 04:52:27.079 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:ARRIBA_VISUALISATION (E5087.normal); work-dir=/data2/USERS/villemin/Myelome/fusion/work/7f/37152b0171cbe2c7bf012aabf78b73
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:ARRIBA_VISUALISATION (E5087.normal)` failed
nov.-28 04:52:27.160 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:ARRIBA_VISUALISATION (E5087.normal)'

Caused by:
  Process exceeded running time limit (8h)

Command executed:

  draw_fusions.R \
      --fusions=E5087.normal.FusionInspector.fusions.tsv \
      --alignments=E5087.normal.Aligned.sortedByCoord.out.bam \
      --output=E5087.normal_combined_fusions_arriba_visualisation.pdf \
      --annotation=Homo_sapiens.GRCh38.109.chr.gtf \
       --cytobands=cytobands_hg38_GRCh38_v2.3.0.tsv \
      --proteinDomains=protein_domains_hg38_GRCh38_v2.3.0.gff3 \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:ARRIBA_VISUALISATION":
      arriba: $(arriba -h | grep 'Version:' 2>&1 |  sed 's/Version: //')
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)

Command error:
  Drawing fusion #1319: TKT:UBE2E3
  Drawing fusion #1320: TM7SF3:FAR2
  Drawing fusion #1321: TMBIM1:DTX2
  Drawing fusion #1322: TMC6:RUNX3
  Drawing fusion #1323: TMCC3:DNAJC5
  Drawing fusion #1324: TNFAIP8:HSD17B4
  Drawing fusion #1325: TNFAIP8:ITK
  Drawing fusion #1326: TNFAIP8:MATR3
  Drawing fusion #1327: TNFRSF10B:EGR3
  Drawing fusion #1328: TNFRSF10C:HNRNPH3
  Drawing fusion #1329: TNFRSF10C:ISCA1
  Drawing fusion #1330: TNFRSF1B:TGIF2
  Drawing fusion #1331: TNFSF10:PICALM
  Drawing fusion #1332: TNIP2:SET
  Drawing fusion #1333: TNKS:NUDCD1
  Drawing fusion #1334: TNRC18:BRI3
  Drawing fusion #1335: TNRC18:EEF1D
  Drawing fusion #1336: TNRC6A:TPM3
  Drawing fusion #1337: TOLLIP:ACAP3
  Drawing fusion #1338: TOR1AIP2:SECISBP2L
  Drawing fusion #1339: TPI1:CASTOR1
  Drawing fusion #1340: TPI1:RBM4
  Drawing fusion #1341: TPK1:ARHGAP15
  Drawing fusion #1342: TPM3:UBAP2L
  Drawing fusion #1343: TPM4:LPAR2
  Drawing fusion #1344: TPM4:NSD3
  Drawing fusion #1345: TPM4:R3HDM4
  Drawing fusion #1346: TPM4:RBM38
  Drawing fusion #1347: TPR:ACAP2
  Drawing fusion #1348: TRA2B:FUS
  Drawing fusion #1349: TRAF2:TSC22D3
  Drawing fusion #1350: TRAF3:HP1BP3
  Drawing fusion #1351: TRAF7:ATP6V0C
  Drawing fusion #1352: TRAM2:MYH9
  Drawing fusion #1353: TREM1:BAZ1A
  Drawing fusion #1354: TREM1:KCTD20
  Drawing fusion #1355: TREM1:TMEM71
  Drawing fusion #1356: TSEN34:SH3BP2
  Drawing fusion #1357: TSNARE1:SELENOO
  Drawing fusion #1358: TSPAN4:TNK2
  Drawing fusion #1359: TTYH3:AKT1
  Drawing fusion #1360: TUBA1A:LPCAT1
  Drawing fusion #1361: TUBB:CNIH4
  Drawing fusion #1362: TUBGCP6:ANKLE2
  Drawing fusion #1363: TVP23C:TTC39C
  Drawing fusion #1364: TXLNG:PLP2
  Drawing fusion #1365: TXNIP:QRICH1
  Drawing fusion #1366: TYROBP:TLR2
  Drawing fusion #1367: TYW3:NRDC
  Drawing fusion #1368: U2AF1:ACAP2

Work dir:
  /data2/USERS/villemin/Myelome/fusion/work/7f/37152b0171cbe2c7bf012aabf78b73

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Relevant files

[nextflow.log](https://github.com/nf-core/rnafusion/files/13486458/nextflow.log)

### System information

Nextflow version (eg. 23.04.0)
Hardware : HPC
Executor : local
Container engine: Singularity
OS : Linux Ubuntu
Version of nf-core/rnafusion 2.4

**Comment by rannick** [comment] 2023-11-29 10:52
Recurrent for this sample or over multiple ones?

**Comment by ZheFrench** [comment] 2023-11-29 11:04
For now, It just happened also on another one.

**Comment by rannick** [comment] 2023-11-29 11:07
And is the amount of fusions in E5087.normal.FusionInspector.fusions.tsv unusually large?

**Comment by ZheFrench** [comment] 2023-11-29 11:18
Yeah it's among  the big ones with 55 Mo but I got one around 57 Mo who succeed.
The other one who failed was 23 Mo.

**Comment by ZheFrench** [comment] 2023-12-13 08:32
So where in the code can I increase this value of 8h : 
_Process exceeded running time limit (8h)_

**Comment by rannick** [comment] 2023-12-19 15:01
Sorry, I started typing an answer but never finished: you can ovrewrite the process requirements with:
    withName:'ARRIBA_VISUALISATION' {
        memory = { check_max( 12.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 4.h  * task.attempt, 'time'    ) }
        cpus = 1
    }

in a .config file passed with -c

**Comment by ZheFrench** [comment] 2024-01-19 08:37
Did not help...still have this bug for a few set of samples.

**Comment by rannick** [comment] 2024-03-15 13:45
So, it does not seem to be a running time problem, but something else is happening with some samples. It is very difficult for me to reproduce without the samples. If you can send them I can have a look, otherwise what you can do is investigate what is different for those samples. The bam files are the visualisation's input so you can check there for missing fields of something like that. You can also try to run arriba visualisation as a standalone: https://github.com/suhrig/arriba/blob/master/documentation/visualization.md

**Comment by rannick** [comment] 2024-03-15 13:45
I add the label won't fix for now, because there is nothing we can do without more info

**Closed** 2024-10-10 11:50 UTC
Labels: bug, wontfix
